### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Alex-TIMEHACK**
Added a new notepad app - now it should work without conflicts

### CODE REVIEW

**Comment by lempamo** [comment]
umm, i already added a notepad app

**Comment by Alex-TIMEHACK** [comment]
What are all these conflicts?!

**Comment by Alex-TIMEHACK** [comment]
Did you?

**Comment by Alex-TIMEHACK** [comment]
Damn it

**Comment by Alex-TIMEHACK** [comment]
I wanted to do something for TimeHACK so bad

**Comment by aren-cllc** [comment]
@Alex-TIMEHACK Your local repo is broken with merge conflicts, you should reclone
I don't see the point to this pull request, closing it...

**Pull request closed without merging**
